version: '3'

services:
  vaultwarden:
    image: docker.io/vaultwarden/server:alpine
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      WEBSOCKET_ENABLED: "true"
    volumes:
      - ./vaultwarden/data:/data
  ocis:
    image: docker.io/owncloud/ocis:2.0.0-beta.8
    container_name: ocis
    restart: unless-stopped
    environment:
      PROXY_TLS: "false"
      OCIS_URL: "https://ocis.apps.wooseop.kim"
    volumes:
      - ./ocis/config:/etc/ocis:ro
      - ./ocis/data:/var/lib/ocis
  caddy:
    image: docker.io/caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/config:/config
      - ./caddy/data:/data
  restic:
    build: ./restic
    container_name: restic
    restart: unless-stopped
    env_file: ./restic/.env
    volumes:
      - .:/data:ro

