version: "3"

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    network_mode: host
    pid: host
    restart: always
    volumes:
      - /:/host:ro,rslave
    command:
      - "--path.rootfs=/host"
  prometheus:
    image: quay.io/prometheus/prometheus:latest
    container_name: prometheus
    restart: always
    extra_hosts:
      host.docker.internal: host-gateway
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/data:/prometheus:rslave
  grafana:
    image: docker.io/grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./grafana/data:/var/lib/grafana
  vaultwarden:
    image: docker.io/vaultwarden/server:alpine
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      WEBSOCKET_ENABLED: true
      SIGNUPS_ALLOWED: false
    volumes:
      - ./vaultwarden/data:/data
  gitea:
    image: docker.io/gitea/gitea:1
    container_name: gitea
    restart: unless-stopped
    environment:
      GITEA__service__DISABLE_REGISTRATION: true
    volumes:
      - ./gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  caddy:
    image: docker.io/caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    env_file: ./caddy/.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/config/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/config/generated:/config
      - ./caddy/data:/data
  restic:
    image: docker.io/wooseopkim/restic:latest
    container_name: restic
    restart: always
    env_file: ./restic/.env
    entrypoint: /entrypoint.sh
    volumes:
      - .:/data:ro
      - ./restic/entrypoint.sh:/entrypoint.sh:ro
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 0 * * *"

