version: '3'

services:
  vaultwarden:
    image: docker.io/vaultwarden/server:alpine
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      WEBSOCKET_ENABLED: "true"
    volumes:
      - ./vaultwarden/data:/data
  etesync:
    build:
      context: ./etesync
      args:
        ETESYNC_TAG: v0.10.0
    container_name: etesync
    restart: unless-stopped
    volumes:
      - ./etesync/config:/config:ro
      - ./etesync/data:/data
  caddy:
    image: docker.io/caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/config/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/config/generated:/config
      - ./caddy/data:/data
  restic:
    build: ./restic
    container_name: restic
    restart: unless-stopped
    env_file: ./restic/.env
    volumes:
      - .:/data:ro
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 0 * * *"

