name: Deploy

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare for CI
        run: |
          find -name '.env.example' -type f | \
            sed 's/\(.\+\).example/cp \1.example \1/g' | \
            xargs -I % bash -c %
      - name: Check if everything works
        uses: hoverkraft-tech/compose-action@v2.0.0

      - name: Deploy
        run: |
          eval `ssh-agent -s`
          echo "$SSH_PRIVATE_KEY" | ssh-add -
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -t rsa "$SSH_HOST" >> ~/.ssh/known_hosts
          cat ./apply.sh | ssh "$SSH_USER"@"$SSH_HOST"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

